const shopActionsTypes = {
  FETCHING_COLLECTION_START: " FETCHING_COLLECTION_START:",
  FETCHING_COLLECTION_SUCCESS: "FETCHING_COLLECTION_SUCCESS",
  FETCHING_COLLECTION_FAILURE: "FETCHING_COLLECTION_FAILURE"
};

export default shopActionsTypes;
